// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdateAndRestart() {
  return window['go']['main']['App']['ApplyUpdateAndRestart']();
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['App']['CancelUpdateDownload']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearMedia() {
  return window['go']['main']['App']['ClearMedia']();
}

export function CurrentMediaURL() {
  return window['go']['main']['App']['CurrentMediaURL']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExportVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportVideo'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetMediaInfo() {
  return window['go']['main']['App']['GetMediaInfo']();
}

export function GetPendingUpdate() {
  return window['go']['main']['App']['GetPendingUpdate']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenVideoDialog() {
  return window['go']['main']['App']['OpenVideoDialog']();
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}
