// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function ClearMedia() {
  return window['go']['main']['App']['ClearMedia']();
}

export function CurrentMediaURL() {
  return window['go']['main']['App']['CurrentMediaURL']();
}

export function ExportVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportVideo'](arg1, arg2, arg3);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetMediaInfo() {
  return window['go']['main']['App']['GetMediaInfo']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenVideoDialog() {
  return window['go']['main']['App']['OpenVideoDialog']();
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}
