// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {video} from '../models';

export function ApplyUpdateAndRestart():Promise<void>;

export function CancelExport():Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function CheckUpdate():Promise<updater.UpdateInfo>;

export function ClearMedia():Promise<void>;

export function CurrentMediaURL():Promise<string>;

export function DownloadUpdate(arg1:boolean):Promise<void>;

export function ExportVideo(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetEnv():Promise<main.EnvInfo>;

export function GetMediaInfo():Promise<video.MediaInfo>;

export function GetPendingUpdate():Promise<updater.UpdateInfo>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenVideoDialog():Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;
