// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {video} from '../models';

export function CancelExport():Promise<void>;

export function CurrentMediaURL():Promise<string>;

export function ExportVideo(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetEnv():Promise<main.EnvInfo>;

export function GetMediaInfo():Promise<video.MediaInfo>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenVideoDialog():Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;
